site_name: Dragon Framework Docs
repo_url: https://github.com/red-scale-dragon/docs/
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - open-in-new-tab
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition